#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/Users/borismarin/src/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/Users/borismarin/src/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/Users/borismarin/git/retina/PublioEtAl2009/x86_64/.libs/libnrnmech.so" "$@"
